export {
  searchAll,
  searchManuscripts,
  getManuscriptById,
  getAutocomplete,
  getPopularKeywords,
  getSearchHistory,
  addSearchHistory,
  deleteSearchHistory,
  clearSearchHistory,
  getBookmarks,
  addBookmark,
  removeBookmark,
  getStats,
  updateManuscript,
  deleteManuscript,
} from './searchApi';
