export const MODEL_OPTIONS = [
  // { label: 'TEST', value: 'test' },
  // { label: 'GPT5.2', value: 'gpt-5-2' },
  // { label: 'GPT5', value: 'gpt-5-v2' },
  // { label: 'GPT4O', value: 'gpt-4-v3' },
  // { label: 'GEM', value: 'gemini-3-pro' },
  // { label: 'GROK', value: 'grok' },
  // { label: 'CLAUDE', value: 'claude' },
  // { label: 'CLEAN_CLAUDE', value: 'clean-claude' },
  // { label: 'DS', value: 'deepseek' },
  // { label: 'GPT5.2_NEW', value: 'openai-new' },
  { label: 'GEM_NEW', value: 'gemini-new' },
  // { label: 'DS_NEW', value: 'deepseek-new' },
  // { label: 'GROK_NEW', value: 'grok-new' },
  // { label: 'CLEAN_DEEPSEEK', value: 'clean-deepseek' },
  // { label: 'GPT5.1_맛집', value: 'restaurant-gpt5' },
  // { label: 'GPT4O_맛집', value: 'restaurant-oai-4' },
  // { label: 'GEM_맛집', value: 'restaurant' },
  // { label: 'GROK_맛집', value: 'restaurant-grok' },
  // { label: 'CLAUDE_맛집', value: 'restaurant-claude' },
  // { label: 'DEEPSEEK_맛집', value: 'restaurant-deepseek' },
  // { label: 'SOLAR', value: 'solar' },
  // { label: 'SOLAR_CLEAN', value: 'solar-ver3-clean' },
  // { label: 'GPT_CLEAN', value: 'gpt-ver3-clean' },
  // { label: 'GROK_CLEAN', value: 'grok-ver3-clean' },
  // { label: 'GEM3_FLASH', value: 'gemini-3-flash' },
  // { label: 'GEM3_FLASH_CLEAN', value: 'gemini-3-flash-clean' },
] as const;

export type ChatService = (typeof MODEL_OPTIONS)[number]['value'];
