import { defineStore } from 'pinia';
import { ref, computed } from 'vue';
import type {
  LoginStatus,
  LogType,
  LogEntry,
  UploadedFolder,
  NaverAccount,
} from '@/types';

export const useBotStore = defineStore('bot', () => {
  // 계정 목록 (상수)
  const ACCOUNTS: NaverAccount[] = [
    {
      id: 'ganggyunggyu',
      password: '12Qwaszx!@',
    },
  ];

  // 로그 관련
  const logs = ref<LogEntry[]>([]);

  // 로그인 관련
  const sessionId = ref<string | null>(null);
  const cookies = ref<Record<string, string> | null>(null);
  const loginStatus = ref<LoginStatus>('LOGGED_OUT');
  const currentAccountIndex = ref(0);
  const isLoginLoading = ref(false);
  const useManualAccount = ref(false);
  const manualId = ref('');
  const manualPassword = ref('');

  // 봇 설정
  const isPublishing = ref(false);
  const isBotRunning = ref(false);
  const publishCount = ref(5);
  const postsPerAccount = ref(10);
  const autoGenerateDraft = ref(false);
  const autoSchedule = ref(false);

  // 원고 생성 설정
  const keywords = ref('');
  const service = ref('');
  const refText = ref('');
  const generateImages = ref(true);
  const imageCount = ref(5);
  const delayBetweenPosts = ref(60);

  // 폴더 업로드
  const uploadedFolderList = ref<UploadedFolder[]>([]);
  const isUploading = ref(false);
  const isDragOver = ref(false);

  // 스케줄 설정
  const now = new Date();
  const today = now.toISOString().split('T')[0];
  const nextHour = (now.getHours() + 1) % 24;
  const scheduleDate = ref(today);
  const scheduleStartHour = ref(nextHour);
  const scheduleIntervalHours = ref(1);
  const scheduleIntervalMinutes = ref(0);

  // Computed
  const currentAccount = computed(() => {
    if (useManualAccount.value) {
      return { id: manualId.value.trim(), password: manualPassword.value };
    }
    return ACCOUNTS[currentAccountIndex.value] || null;
  });

  const keywordList = computed(() =>
    keywords.value
      .split(/[\n,]+/)
      .map((k) => k.trim())
      .filter(Boolean)
  );

  const loginStatusLabel = computed(
    () =>
      ({
        LOGGED_OUT: '로그아웃',
        LOGGING_IN: '로그인 중...',
        LOGGED_IN: '로그인됨',
        ERROR: '오류',
      }[loginStatus.value])
  );

  const loginStatusBadgeClass = computed(
    () =>
      ({
        LOGGED_OUT: 'bg-slate-500/20 text-slate-400',
        LOGGING_IN: 'bg-amber-500/20 text-amber-400 animate-pulse',
        LOGGED_IN: 'bg-emerald-500/20 text-emerald-400',
        ERROR: 'bg-red-500/20 text-red-400',
      }[loginStatus.value])
  );

  return {
    // 상수
    ACCOUNTS,
    today,

    // 로그
    logs,

    // 로그인
    sessionId,
    cookies,
    loginStatus,
    currentAccountIndex,
    isLoginLoading,
    useManualAccount,
    manualId,
    manualPassword,

    // 봇 설정
    isPublishing,
    isBotRunning,
    publishCount,
    postsPerAccount,
    autoGenerateDraft,
    autoSchedule,

    // 원고 생성
    keywords,
    service,
    refText,
    generateImages,
    imageCount,
    delayBetweenPosts,

    // 폴더 업로드
    uploadedFolderList,
    isUploading,
    isDragOver,

    // 스케줄
    scheduleDate,
    scheduleStartHour,
    scheduleIntervalHours,
    scheduleIntervalMinutes,

    // Computed
    currentAccount,
    keywordList,
    loginStatusLabel,
    loginStatusBadgeClass,
  };
});
