<script setup lang="ts">
import { onMounted } from 'vue';
import { storeToRefs } from 'pinia';
import { Button, Switch, Card } from '@/components/ui';
import {
  useBotStore,
  useBotLog,
  useBotLogin,
  useFolderUpload,
  useBotActions,
} from '@/features/bot';

const botStore = useBotStore();
const { ACCOUNTS, today } = botStore;
const {
  logs,
  loginStatus,
  isLoginLoading,
  useManualAccount,
  manualId,
  manualPassword,
  currentAccountIndex,
  isPublishing,
  isBotRunning,
  autoGenerateDraft,
  autoSchedule,
  keywords,
  service,
  refText,
  generateImages,
  imageCount,
  delayBetweenPosts,
  uploadedFolderList,
  isUploading,
  isDragOver,
  scheduleDate,
  scheduleStartHour,
  scheduleIntervalHours,
  scheduleIntervalMinutes,
  keywordList,
  loginStatusLabel,
  loginStatusBadgeClass,
} = storeToRefs(botStore);

const {
  logContainer,
  clearLogs,
  formatTime,
  getLogBgClass,
  getLogTextClass,
  getLogIcon,
} = useBotLog();

const { handleLogin, handleLogout, checkAuthApiHealth } = useBotLogin();
const {
  handleDragOver,
  handleDragLeave,
  handleDrop,
  removeFolder,
  clearFolderList,
  handleUploadFolders,
} = useFolderUpload();
const { handlePublish, handleStartBot, handleStopBot, handleAutoBot } =
  useBotActions();

onMounted(() => {
  const { addLog } = useBotLog();
  addLog('INFO', '봇 페이지 초기화');
  checkAuthApiHealth();
});
</script>

<template>
  <div
    class="p-6 min-h-screen bg-gradient-to-br from-[#0f0f1a] via-[#1a1a2e] to-[#16213e]"
  >
    <div
      class="grid grid-cols-[380px_1fr] gap-6 max-w-[1400px] mx-auto h-[calc(100vh-48px)] max-md:grid-cols-1 max-md:h-auto"
    >
      <!-- 왼쪽: 설정 패널 -->
      <div class="h-full overflow-hidden max-md:h-auto">
        <Card
          class="h-full bg-white/3 backdrop-blur-[10px] border border-white/8 rounded-2xl overflow-hidden p-0!"
        >
          <!-- 로그인 섹션 -->
          <div class="p-5 px-6">
            <div class="flex justify-between items-center mb-4">
              <h3
                class="text-sm font-semibold text-slate-400 uppercase tracking-wide"
              >
                네이버 계정
              </h3>
              <span
                :class="[
                  'px-2.5 py-1 rounded-full text-[11px] font-semibold uppercase',
                  loginStatusBadgeClass,
                ]"
                >{{ loginStatusLabel }}</span
              >
            </div>

            <!-- 계정 모드 토글 -->
            <div class="flex gap-1 p-1 bg-slate-900/40 rounded-lg mb-3.5">
              <button
                :class="[
                  'flex-1 py-2 px-3 text-xs font-medium rounded-md transition-all',
                  !useManualAccount
                    ? 'bg-indigo-500/30 text-slate-200'
                    : 'text-slate-400 hover:text-slate-200',
                ]"
                @click="useManualAccount = false"
              >
                프리셋
              </button>
              <button
                :class="[
                  'flex-1 py-2 px-3 text-xs font-medium rounded-md transition-all',
                  useManualAccount
                    ? 'bg-indigo-500/30 text-slate-200'
                    : 'text-slate-400 hover:text-slate-200',
                ]"
                @click="useManualAccount = true"
              >
                직접입력
              </button>
            </div>

            <!-- 프리셋 모드 -->
            <div
              v-if="!useManualAccount"
              class="flex justify-between items-center gap-4"
            >
              <div class="flex flex-col gap-0.5">
                <span class="text-[15px] font-medium text-slate-200">{{
                  ACCOUNTS[currentAccountIndex]?.id || '계정 없음'
                }}</span>
                <span
                  v-if="ACCOUNTS.length > 1"
                  class="text-[11px] text-slate-500"
                  >{{ currentAccountIndex + 1 }} / {{ ACCOUNTS.length }}</span
                >
              </div>
              <Button
                v-if="loginStatus !== 'LOGGED_IN'"
                size="sm"
                color="primary"
                :loading="isLoginLoading"
                class="min-w-[80px]"
                @click="handleLogin"
                >로그인</Button
              >
              <Button
                v-else
                size="sm"
                color="light"
                :loading="isLoginLoading"
                class="min-w-[80px]"
                @click="handleLogout"
                >로그아웃</Button
              >
            </div>

            <!-- 직접입력 모드 -->
            <div v-else class="flex flex-col gap-2.5">
              <input
                v-model="manualId"
                type="text"
                class="h-[38px] px-3 bg-slate-900/60 border border-white/10 rounded-lg text-sm text-slate-200 placeholder:text-slate-500 focus:outline-none focus:border-indigo-500 focus:ring-2 focus:ring-indigo-500/20 transition-all"
                placeholder="네이버 아이디"
                :disabled="loginStatus === 'LOGGED_IN'"
              />
              <input
                v-model="manualPassword"
                type="password"
                class="h-[38px] px-3 bg-slate-900/60 border border-white/10 rounded-lg text-sm text-slate-200 placeholder:text-slate-500 focus:outline-none focus:border-indigo-500 focus:ring-2 focus:ring-indigo-500/20 transition-all"
                placeholder="비밀번호"
                :disabled="loginStatus === 'LOGGED_IN'"
              />
              <Button
                v-if="loginStatus !== 'LOGGED_IN'"
                size="sm"
                color="primary"
                display="full"
                :loading="isLoginLoading"
                :disabled="!manualId || !manualPassword"
                @click="handleLogin"
                >로그인</Button
              >
              <Button
                v-else
                size="sm"
                color="light"
                display="full"
                :loading="isLoginLoading"
                @click="handleLogout"
                >로그아웃</Button
              >
            </div>
          </div>

          <div
            class="h-px bg-gradient-to-r from-transparent via-white/10 to-transparent"
          />

          <!-- 옵션 섹션 -->
          <div class="p-5 px-6">
            <h3
              class="text-sm font-semibold text-slate-400 uppercase tracking-wide mb-4"
            >
              발행 옵션
            </h3>
            <div class="flex flex-col gap-3">
              <label
                class="flex items-center gap-3.5 p-3.5 px-4 bg-white/2 border border-white/6 rounded-xl cursor-pointer hover:bg-white/4 hover:border-white/10 transition-all"
              >
                <Switch v-model="autoGenerateDraft" size="sm" />
                <div class="flex flex-col gap-0.5">
                  <span class="text-sm font-medium text-slate-200"
                    >원고 자동생성</span
                  >
                  <span class="text-[11px] text-slate-500">{{
                    autoGenerateDraft ? 'AI 원고 생성' : '로컬 원고 사용'
                  }}</span>
                </div>
              </label>
              <label
                class="flex items-center gap-3.5 p-3.5 px-4 bg-white/2 border border-white/6 rounded-xl cursor-pointer hover:bg-white/4 hover:border-white/10 transition-all"
              >
                <Switch v-model="autoSchedule" size="sm" />
                <div class="flex flex-col gap-0.5">
                  <span class="text-sm font-medium text-slate-200"
                    >예약 발행</span
                  >
                  <span class="text-[11px] text-slate-500"
                    >지정 시간에 발행</span
                  >
                </div>
              </label>
            </div>
          </div>

          <!-- 로컬 원고 업로드 -->
          <div
            v-if="!autoGenerateDraft"
            class="p-5 px-6 bg-blue-500/5 border-y border-blue-500/10"
          >
            <h3
              class="text-sm font-semibold text-slate-400 uppercase tracking-wide mb-4"
            >
              원고 폴더 업로드
            </h3>
            <div
              :class="[
                'flex flex-col items-center justify-center p-8 border-2 border-dashed rounded-xl transition-all cursor-pointer',
                isDragOver
                  ? 'border-indigo-500 bg-indigo-500/10'
                  : 'border-white/20 hover:border-white/30 bg-slate-900/40',
              ]"
              @dragover="handleDragOver"
              @dragleave="handleDragLeave"
              @drop="handleDrop"
            >
              <span class="text-3xl mb-2">📁</span>
              <p class="text-sm font-medium text-slate-200">
                폴더를 여기에 드래그하세요
              </p>
              <p class="text-[11px] text-slate-500 mt-1">
                폴더 안에 원고.txt + images/ 구조
              </p>
            </div>
            <div v-if="uploadedFolderList.length > 0" class="mt-4">
              <div class="flex justify-between items-center mb-2">
                <span class="text-xs font-medium text-slate-400"
                  >{{ uploadedFolderList.length }}개 폴더</span
                >
                <button
                  class="text-[11px] text-red-400 border border-red-500/30 px-2 py-1 rounded hover:bg-red-500/10 transition-all"
                  @click="clearFolderList"
                >
                  전체 삭제
                </button>
              </div>
              <ul class="flex flex-col gap-1.5 max-h-[150px] overflow-y-auto">
                <li
                  v-for="(folder, index) in uploadedFolderList"
                  :key="folder.name"
                  class="flex justify-between items-center p-2.5 px-3 bg-white/3 border border-white/6 rounded-lg"
                >
                  <div class="flex items-center gap-2.5">
                    <span class="text-[13px] font-medium text-slate-200">{{
                      folder.name
                    }}</span>
                    <span class="text-[11px] text-slate-500"
                      >{{ folder.manuscriptFile ? '📄' : '❌' }}
                      {{ folder.imageFiles.length }}장</span
                    >
                  </div>
                  <button
                    class="w-5 h-5 flex items-center justify-center text-slate-400 hover:text-red-400 transition-colors"
                    @click="removeFolder(index)"
                  >
                    ×
                  </button>
                </li>
              </ul>
              <Button
                display="full"
                size="md"
                color="primary"
                :loading="isUploading"
                class="mt-3"
                @click="handleUploadFolders"
                >서버에 업로드</Button
              >
            </div>
          </div>

          <!-- 원고 자동생성 설정 -->
          <div
            v-if="autoGenerateDraft"
            class="p-5 px-6 bg-emerald-500/5 border-y border-emerald-500/10"
          >
            <h3
              class="text-sm font-semibold text-slate-400 uppercase tracking-wide mb-4"
            >
              원고 생성 설정
            </h3>
            <div class="flex flex-col gap-3.5">
              <div class="flex flex-col gap-1.5">
                <label
                  class="text-[11px] font-medium text-slate-400 uppercase tracking-wide"
                  >키워드 (필수)</label
                >
                <textarea
                  v-model="keywords"
                  class="p-3 bg-slate-900/60 border border-white/10 rounded-lg text-[13px] text-slate-200 placeholder:text-slate-500 resize-y min-h-[80px] focus:outline-none focus:border-emerald-500 focus:ring-2 focus:ring-emerald-500/20 transition-all font-sans"
                  placeholder="키워드 입력 (줄바꿈 또는 쉼표로 구분)"
                  rows="4"
                />
                <span class="text-[10px] text-emerald-400 text-right"
                  >{{ keywordList.length }}개 키워드</span
                >
              </div>
              <div class="grid grid-cols-2 gap-3">
                <div class="flex flex-col gap-1.5">
                  <label
                    class="text-[11px] font-medium text-slate-400 uppercase tracking-wide"
                    >카테고리</label
                  >
                  <input
                    v-model="service"
                    type="text"
                    class="h-10 px-3 bg-slate-900/60 border border-white/10 rounded-lg text-sm text-slate-200 focus:outline-none focus:border-emerald-500 focus:ring-2 focus:ring-emerald-500/20 transition-all"
                    placeholder="예: 위고비"
                  />
                </div>
                <div class="flex flex-col gap-1.5">
                  <label
                    class="text-[11px] font-medium text-slate-400 uppercase tracking-wide"
                    >이미지 수</label
                  >
                  <input
                    v-model.number="imageCount"
                    type="number"
                    min="1"
                    max="10"
                    class="h-10 px-3 bg-slate-900/60 border border-white/10 rounded-lg text-sm text-slate-200 focus:outline-none focus:border-emerald-500 focus:ring-2 focus:ring-emerald-500/20 transition-all"
                  />
                </div>
              </div>
              <div class="flex flex-col gap-1.5">
                <label
                  class="text-[11px] font-medium text-slate-400 uppercase tracking-wide"
                  >참조 원고 (선택)</label
                >
                <textarea
                  v-model="refText"
                  class="p-3 bg-slate-900/60 border border-white/10 rounded-lg text-[13px] text-slate-200 placeholder:text-slate-500 resize-y min-h-[60px] focus:outline-none focus:border-emerald-500 focus:ring-2 focus:ring-emerald-500/20 transition-all font-sans"
                  placeholder="참조할 원고 내용 (선택)"
                  rows="3"
                />
              </div>
              <div class="grid grid-cols-2 gap-3 items-center">
                <label
                  class="flex items-center gap-2 text-[13px] text-slate-200 cursor-pointer"
                >
                  <Switch v-model="generateImages" size="sm" />
                  <span>이미지 생성</span>
                </label>
                <div class="flex items-center gap-2">
                  <label
                    class="text-[11px] font-medium text-slate-400 whitespace-nowrap"
                    >대기시간(초)</label
                  >
                  <input
                    v-model.number="delayBetweenPosts"
                    type="number"
                    min="10"
                    max="300"
                    class="w-[70px] h-8 px-2 bg-slate-900/60 border border-white/10 rounded-md text-[13px] text-slate-200 text-center focus:outline-none focus:border-emerald-500 transition-all"
                  />
                </div>
              </div>
            </div>
          </div>

          <!-- 예약 설정 -->
          <div
            v-if="autoSchedule"
            class="p-5 px-6 bg-indigo-500/5 border-y border-indigo-500/10"
          >
            <h3
              class="text-sm font-semibold text-slate-400 uppercase tracking-wide mb-4"
            >
              예약 설정
            </h3>
            <div class="grid grid-cols-2 gap-3.5">
              <div class="flex flex-col gap-1.5">
                <label
                  class="text-[11px] font-medium text-slate-400 uppercase tracking-wide"
                  >발행 날짜</label
                >
                <input
                  v-model="scheduleDate"
                  type="date"
                  :min="today"
                  class="h-10 px-3 bg-slate-900/60 border border-white/10 rounded-lg text-sm text-slate-200 focus:outline-none focus:border-indigo-500 focus:ring-2 focus:ring-indigo-500/20 transition-all [color-scheme:dark]"
                />
              </div>
              <div class="flex flex-col gap-1.5">
                <label
                  class="text-[11px] font-medium text-slate-400 uppercase tracking-wide"
                  >시작 시간</label
                >
                <div class="flex items-center gap-2">
                  <input
                    v-model.number="scheduleStartHour"
                    type="number"
                    min="0"
                    max="23"
                    class="w-[70px] h-10 px-3 bg-slate-900/60 border border-white/10 rounded-lg text-sm text-slate-200 text-center focus:outline-none focus:border-indigo-500 focus:ring-2 focus:ring-indigo-500/20 transition-all"
                  />
                  <span class="text-[13px] text-slate-500">시</span>
                </div>
              </div>
              <div class="flex flex-col gap-1.5">
                <label
                  class="text-[11px] font-medium text-slate-400 uppercase tracking-wide"
                  >간격 (시간)</label
                >
                <input
                  v-model.number="scheduleIntervalHours"
                  type="number"
                  min="0"
                  max="24"
                  class="h-10 px-3 bg-slate-900/60 border border-white/10 rounded-lg text-sm text-slate-200 focus:outline-none focus:border-indigo-500 focus:ring-2 focus:ring-indigo-500/20 transition-all"
                />
              </div>
              <div class="flex flex-col gap-1.5">
                <label
                  class="text-[11px] font-medium text-slate-400 uppercase tracking-wide"
                  >간격 (분)</label
                >
                <input
                  v-model.number="scheduleIntervalMinutes"
                  type="number"
                  min="0"
                  max="59"
                  class="h-10 px-3 bg-slate-900/60 border border-white/10 rounded-lg text-sm text-slate-200 focus:outline-none focus:border-indigo-500 focus:ring-2 focus:ring-indigo-500/20 transition-all"
                />
              </div>
            </div>
            <p class="mt-3 text-[11px] text-slate-500 text-center">
              분 값이 0보다 크면 분 단위가 우선 적용됩니다
            </p>
          </div>

          <div
            class="h-px bg-gradient-to-r from-transparent via-white/10 to-transparent"
          />

          <!-- 액션 버튼 -->
          <div class="mt-auto p-5 px-6 pb-6">
            <div class="flex gap-3">
              <template v-if="!autoGenerateDraft">
                <Button
                  size="md"
                  color="primary"
                  :loading="isPublishing"
                  :disabled="loginStatus !== 'LOGGED_IN' || isBotRunning"
                  class="flex-1 h-11 font-semibold"
                  @click="handlePublish"
                  >발행하기</Button
                >
                <Button
                  v-if="!isBotRunning"
                  size="md"
                  color="primary"
                  :disabled="isPublishing"
                  class="flex-1 h-11 font-semibold"
                  @click="handleStartBot"
                  >자동화 시작</Button
                >
              </template>
              <template v-else>
                <Button
                  v-if="!isBotRunning"
                  size="md"
                  color="primary"
                  :disabled="keywordList.length === 0"
                  class="flex-1 h-11 font-semibold"
                  @click="handleAutoBot"
                  >원고생성 + 발행 시작</Button
                >
              </template>
              <Button
                v-if="isBotRunning"
                size="md"
                color="danger"
                class="flex-1 h-11 font-semibold"
                @click="handleStopBot"
                >중지</Button
              >
            </div>
          </div>
        </Card>
      </div>

      <!-- 오른쪽: 로그 패널 -->
      <div class="h-full overflow-hidden max-md:h-[400px]">
        <Card
          class="h-full flex flex-col bg-white/3 backdrop-blur-[10px] border border-white/8 rounded-2xl overflow-hidden p-0!"
        >
          <template #header>
            <div
              class="flex justify-between items-center px-5 py-4 border-b border-white/6"
            >
              <h2 class="text-[15px] font-semibold text-slate-200">
                실행 로그
              </h2>
              <button
                class="px-3 py-1.5 text-xs font-medium text-slate-500 bg-white/5 border border-white/8 rounded-md hover:bg-white/8 hover:text-slate-400 transition-all"
                @click="clearLogs"
              >
                지우기
              </button>
            </div>
          </template>
          <div
            ref="logContainer"
            class="flex-1 overflow-y-auto p-4 font-mono text-xs bg-slate-900/40"
          >
            <div
              v-for="log in logs"
              :key="log.id"
              :class="[
                'flex gap-2.5 p-3 rounded-lg mb-1 items-start hover:bg-white/3 transition-colors',
                getLogBgClass(log.type),
              ]"
            >
              <span class="flex-shrink-0 text-[11px]">{{
                getLogIcon(log.type)
              }}</span>
              <span class="flex-shrink-0 text-[11px] text-slate-600">{{
                formatTime(log.timestamp)
              }}</span>
              <span :class="['wrap-break-word', getLogTextClass(log.type)]">{{
                log.message
              }}</span>
              <span
                v-if="log.detail"
                class="text-[11px] text-slate-500 break-all"
                >{{ log.detail }}</span
              >
            </div>
            <div
              v-if="logs.length === 0"
              class="flex items-center justify-center h-full text-slate-600 text-[13px]"
            >
              로그가 없습니다
            </div>
          </div>
        </Card>
      </div>
    </div>
  </div>
</template>
