<script setup lang="ts">
import { ref, computed, onMounted, nextTick } from 'vue';
import axios from 'axios';
import JSZip from 'jszip';
import { Button, Switch, Card } from '@/components/ui';

// Auth API (Playwright 백엔드)
const authApi = axios.create({
  baseURL: import.meta.env.VITE_API_URL || 'http://localhost:8000',
  timeout: 60000,
});

type LoginStatus = 'LOGGED_OUT' | 'LOGGING_IN' | 'LOGGED_IN' | 'ERROR';
type LogType = 'INFO' | 'SUCCESS' | 'ERROR' | 'WARNING';

interface LogEntry {
  id: string;
  type: LogType;
  message: string;
  detail?: string;
  timestamp: number;
}

// 웹 앱에서는 직접입력 모드 사용 (프리셋은 extension에서만 사용)
const ACCOUNTS: Array<{ id: string; password: string }> = [];

// 세션 관리
const sessionId = ref<string | null>(null);
const cookies = ref<Record<string, string> | null>(null);

// 로그
const logs = ref<LogEntry[]>([]);
const logContainer = ref<HTMLElement | null>(null);

const addLog = (type: LogType, message: string, detail?: string) => {
  const entry: LogEntry = {
    id: `${Date.now()}-${Math.random().toString(36).substring(2, 5)}`,
    type,
    message,
    detail,
    timestamp: Date.now(),
  };
  logs.value.push(entry);

  if (logs.value.length > 100) {
    logs.value = logs.value.slice(-100);
  }

  nextTick(() => {
    if (logContainer.value) {
      logContainer.value.scrollTop = logContainer.value.scrollHeight;
    }
  });
};

const clearLogs = () => {
  logs.value = [];
};

// 상태
const loginStatus = ref<LoginStatus>('LOGGED_OUT');
const currentAccountIndex = ref(0);
const isLoginLoading = ref(false);

// 계정 입력 모드 (false: 프리셋, true: 직접입력)
const useManualAccount = ref(false);
const manualId = ref('');
const manualPassword = ref('');

// 현재 사용할 계정
const currentAccount = computed(() => {
  if (useManualAccount.value) {
    return { id: manualId.value.trim(), password: manualPassword.value };
  }
  return ACCOUNTS[currentAccountIndex.value] || null;
});

// 발행 관련
const isPublishing = ref(false);
const isBotRunning = ref(false);
const publishCount = ref(5);
const postsPerAccount = ref(10);

const autoGenerateDraft = ref(false); // false: 로컬 원고 사용, true: 원고 자동생성
const autoSchedule = ref(false);

// 원고 자동생성 옵션
const keywords = ref('');
const service = ref('');
const refText = ref('');
const generateImages = ref(true);
const imageCount = ref(5);
const delayBetweenPosts = ref(60);

// 폴더 업로드 관련
interface UploadedFolder {
  name: string;
  manuscriptFile: File | null;
  imageFiles: File[];
}
const uploadedFolderList = ref<UploadedFolder[]>([]);
const isUploading = ref(false);
const isDragOver = ref(false);

// 드래그앤드랍 핸들러
const handleDragOver = (e: DragEvent) => {
  e.preventDefault();
  isDragOver.value = true;
};

const handleDragLeave = () => {
  isDragOver.value = false;
};

const handleDrop = async (e: DragEvent) => {
  e.preventDefault();
  isDragOver.value = false;

  const items = e.dataTransfer?.items;
  if (!items) return;

  for (const item of Array.from(items)) {
    if (item.kind === 'file') {
      const entry = item.webkitGetAsEntry();
      if (entry?.isDirectory) {
        await processDirectory(entry as FileSystemDirectoryEntry);
      }
    }
  }
};

const processDirectory = async (dirEntry: FileSystemDirectoryEntry) => {
  const folderName = dirEntry.name;
  const folder: UploadedFolder = {
    name: folderName,
    manuscriptFile: null,
    imageFiles: [],
  };

  const readEntries = (reader: FileSystemDirectoryReader): Promise<FileSystemEntry[]> => {
    return new Promise((resolve, reject) => {
      reader.readEntries(resolve, reject);
    });
  };

  const getFile = (fileEntry: FileSystemFileEntry): Promise<File> => {
    return new Promise((resolve, reject) => {
      fileEntry.file(resolve, reject);
    });
  };

  const processEntry = async (entry: FileSystemEntry, path = '') => {
    if (entry.isFile) {
      const fileEntry = entry as FileSystemFileEntry;
      const file = await getFile(fileEntry);
      const fullPath = path + entry.name;

      if (file.name.endsWith('.txt')) {
        folder.manuscriptFile = file;
      } else if (file.type.startsWith('image/') || /\.(jpg|jpeg|png|gif|webp)$/i.test(file.name)) {
        folder.imageFiles.push(file);
      }
    } else if (entry.isDirectory) {
      const dirReader = (entry as FileSystemDirectoryEntry).createReader();
      const entries = await readEntries(dirReader);
      for (const subEntry of entries) {
        await processEntry(subEntry, path + entry.name + '/');
      }
    }
  };

  const reader = dirEntry.createReader();
  const entries = await readEntries(reader);
  for (const entry of entries) {
    await processEntry(entry);
  }

  if (folder.manuscriptFile || folder.imageFiles.length > 0) {
    uploadedFolderList.value.push(folder);
    addLog('INFO', `폴더 추가: ${folderName}`, `원고: ${folder.manuscriptFile ? '있음' : '없음'}, 이미지: ${folder.imageFiles.length}개`);
  }
};

const removeFolder = (index: number) => {
  const removed = uploadedFolderList.value.splice(index, 1);
  if (removed.length > 0) {
    addLog('INFO', `폴더 제거: ${removed[0].name}`);
  }
};

const clearFolderList = () => {
  uploadedFolderList.value = [];
  addLog('INFO', '폴더 목록 초기화');
};

// 폴더들을 ZIP으로 압축해서 업로드
const handleUploadFolders = async () => {
  if (uploadedFolderList.value.length === 0) {
    addLog('ERROR', '업로드할 폴더가 없습니다');
    return;
  }

  isUploading.value = true;
  addLog('INFO', 'ZIP 압축 및 업로드 시작...', `${uploadedFolderList.value.length}개 폴더`);

  try {
    const zip = new JSZip();

    for (const folder of uploadedFolderList.value) {
      const folderZip = zip.folder(folder.name);
      if (!folderZip) continue;

      if (folder.manuscriptFile) {
        const content = await folder.manuscriptFile.text();
        folderZip.file(`${folder.name}.txt`, content);
      }

      if (folder.imageFiles.length > 0) {
        const imagesFolder = folderZip.folder('images');
        for (const img of folder.imageFiles) {
          const buffer = await img.arrayBuffer();
          imagesFolder?.file(img.name, buffer);
        }
      }
    }

    const zipBlob = await zip.generateAsync({ type: 'blob' });
    const formData = new FormData();
    formData.append('file', zipBlob, 'manuscripts.zip');

    const response = await authApi.post('/bot/upload-zip', formData, {
      headers: { 'Content-Type': 'multipart/form-data' },
      timeout: 120000,
    });

    const { success, uploaded = 0, message, error } = response.data;

    if (success) {
      addLog('SUCCESS', '업로드 완료', `${uploaded}개 폴더 업로드됨`);
      uploadedFolderList.value = [];
    } else {
      addLog('ERROR', '업로드 실패', error || message);
    }
  } catch (error: unknown) {
    const axiosError = error as { message?: string };
    addLog('ERROR', '업로드 실패', axiosError.message);
  } finally {
    isUploading.value = false;
  }
};

// 키워드 파싱 (줄바꿈/쉼표 구분)
const keywordList = computed(() => {
  return keywords.value
    .split(/[\n,]+/)
    .map(k => k.trim())
    .filter(Boolean);
});

// 오늘 날짜 & 다음 시간 기본값 (현재 시간은 이미 지났으므로 +1)
const now = new Date();
const today = now.toISOString().split('T')[0];
const nextHour = (now.getHours() + 1) % 24;

const scheduleDate = ref(today);
const scheduleStartHour = ref(nextHour);
const scheduleIntervalHours = ref(1);
const scheduleIntervalMinutes = ref(0);

const loginStatusLabel = computed(() => {
  const labels: Record<LoginStatus, string> = {
    LOGGED_OUT: '로그아웃',
    LOGGING_IN: '로그인 중...',
    LOGGED_IN: '로그인됨',
    ERROR: '오류',
  };
  return labels[loginStatus.value];
});

const loginStatusClass = computed(() => {
  const classes: Record<LoginStatus, string> = {
    LOGGED_OUT: 'status-out',
    LOGGING_IN: 'status-loading',
    LOGGED_IN: 'status-in',
    ERROR: 'status-error',
  };
  return classes[loginStatus.value];
});

const handleLogin = async () => {
  if (isLoginLoading.value) return;

  const account = currentAccount.value;
  if (!account?.id || !account?.password) {
    addLog('ERROR', '계정 정보가 없습니다', useManualAccount.value ? '아이디/비밀번호를 입력하세요' : 'ACCOUNTS 배열에 계정을 추가하세요');
    return;
  }

  isLoginLoading.value = true;
  loginStatus.value = 'LOGGING_IN';
  addLog('INFO', '네이버 로그인 시도 중...', `계정: ${account.id}`);

  try {
    const response = await authApi.post('/auth/naver/login', {
      id: account.id,
      password: account.password,
    });

    const { success, sessionId: sid, cookies: responseCookies, message, error } = response.data;

    if (success) {
      sessionId.value = sid;
      cookies.value = responseCookies || null;
      loginStatus.value = 'LOGGED_IN';
      addLog('SUCCESS', '네이버 로그인 성공', message);
      if (responseCookies) {
        addLog('INFO', '쿠키 저장 완료', `${Object.keys(responseCookies).length}개`);
      }
    } else {
      loginStatus.value = 'ERROR';
      addLog('ERROR', '네이버 로그인 실패', error || message);
    }
  } catch (error: unknown) {
    const axiosError = error as { code?: string; message?: string };
    const isTimeout = axiosError.code === 'ECONNABORTED' || axiosError.message?.includes('timeout');
    loginStatus.value = 'ERROR';
    if (!isTimeout) {
      addLog('ERROR', '네이버 로그인 실패', axiosError.message);
    }
  } finally {
    isLoginLoading.value = false;
  }
};

const handleLogout = async () => {
  if (isLoginLoading.value) return;
  isLoginLoading.value = true;
  addLog('INFO', '네이버 로그아웃 시도 중...');

  try {
    if (sessionId.value) {
      await authApi.post('/auth/naver/logout', {
        sessionId: sessionId.value,
      });
    }

    sessionId.value = null;
    cookies.value = null;
    loginStatus.value = 'LOGGED_OUT';
    addLog('SUCCESS', '네이버 로그아웃 완료');
  } catch (error: unknown) {
    const axiosError = error as { message?: string };
    addLog('WARNING', '로그아웃 API 에러 (로컬 세션은 삭제됨)', axiosError.message);
    sessionId.value = null;
    cookies.value = null;
    loginStatus.value = 'LOGGED_OUT';
  } finally {
    isLoginLoading.value = false;
  }
};

const formatTime = (timestamp: number) => {
  return new Date(timestamp).toLocaleTimeString('ko-KR', {
    hour: '2-digit',
    minute: '2-digit',
    second: '2-digit',
  });
};

const getLogClass = (type: LogType) => {
  const classes: Record<LogType, string> = {
    INFO: 'log-info',
    SUCCESS: 'log-success',
    ERROR: 'log-error',
    WARNING: 'log-warning',
  };
  return classes[type];
};

const getLogIcon = (type: LogType) => {
  const icons: Record<LogType, string> = {
    INFO: 'ℹ️',
    SUCCESS: '✅',
    ERROR: '❌',
    WARNING: '⚠️',
  };
  return icons[type];
};

const checkAuthApiHealth = async () => {
  try {
    const response = await authApi.get('/auth/naver/health');
    if (response.data?.status === 'ok') {
      addLog('SUCCESS', 'Auth API 연결됨', authApi.defaults.baseURL);
    }
  } catch {
    addLog('WARNING', 'Auth API 연결 실패', `${authApi.defaults.baseURL} - 백엔드 서버 실행 필요`);
  }
};

// 발행하기
const handlePublish = async () => {
  if (isPublishing.value) return;

  if (!cookies.value) {
    addLog('ERROR', '발행 실패', '로그인이 필요합니다');
    return;
  }

  isPublishing.value = true;
  addLog('INFO', '블로그 발행 시작...');

  try {
    const response = await authApi.post('/bot/publish', {
      cookies: cookies.value,
      count: publishCount.value,
      auto_generate_draft: autoGenerateDraft.value,
      use_schedule: autoSchedule.value,
      schedule_date: scheduleDate.value || undefined,
      schedule_start_hour: scheduleStartHour.value,
      schedule_interval_hours: scheduleIntervalHours.value,
      schedule_interval_minutes: scheduleIntervalMinutes.value,
    });

    const { success, published = 0, message, error } = response.data;

    if (success) {
      addLog('SUCCESS', '발행 완료', `${published}개 발행됨`);
    } else {
      addLog('ERROR', '발행 실패', error || message);
    }
  } catch (error: unknown) {
    const axiosError = error as { code?: string; message?: string };
    const isTimeout = axiosError.code === 'ECONNABORTED' || axiosError.message?.includes('timeout');
    if (!isTimeout) {
      addLog('ERROR', '발행 실패', axiosError.message);
    }
  } finally {
    isPublishing.value = false;
  }
};

// 전체 자동화 시작
const handleStartBot = async () => {
  if (isBotRunning.value) return;

  if (ACCOUNTS.length === 0) {
    addLog('ERROR', '자동화 실패', '계정 정보가 없습니다');
    return;
  }

  isBotRunning.value = true;
  addLog('INFO', '자동화 봇 시작...', `${ACCOUNTS.length}개 계정`);

  try {
    const response = await authApi.post('/bot/start', {
      accounts: ACCOUNTS.map(acc => ({ id: acc.id, password: acc.password })),
      posts_per_account: postsPerAccount.value,
    });

    const { success, message, error, results } = response.data;

    if (success) {
      addLog('SUCCESS', '자동화 완료', message);
      if (results) {
        results.forEach((r: { account: string; published: number; error?: string }) => {
          if (r.error) {
            addLog('WARNING', `${r.account}`, r.error);
          } else {
            addLog('INFO', `${r.account}`, `${r.published}개 발행`);
          }
        });
      }
    } else {
      addLog('ERROR', '자동화 실패', error || message);
    }
  } catch (error: unknown) {
    const axiosError = error as { code?: string; message?: string };
    const isTimeout = axiosError.code === 'ECONNABORTED' || axiosError.message?.includes('timeout');
    if (!isTimeout) {
      addLog('ERROR', '자동화 실패', axiosError.message);
    }
  } finally {
    isBotRunning.value = false;
  }
};

// 자동화 중지
const handleStopBot = () => {
  addLog('WARNING', '자동화 중지 요청');
  isBotRunning.value = false;
};

// 원고 자동생성 + 발행 (전체 자동화)
const handleAutoBot = async () => {
  if (isBotRunning.value) return;

  const account = currentAccount.value;
  if (!account?.id || !account?.password) {
    addLog('ERROR', '계정 정보가 없습니다', useManualAccount.value ? '아이디/비밀번호를 입력하세요' : 'ACCOUNTS 배열에 계정을 추가하세요');
    return;
  }

  if (keywordList.value.length === 0) {
    addLog('ERROR', '키워드를 입력해주세요');
    return;
  }

  isBotRunning.value = true;
  addLog('INFO', '전체 자동화 시작...', `${keywordList.value.length}개 키워드`);

  try {
    const response = await authApi.post('/bot/auto', {
      account: { id: account.id, password: account.password },
      keywords: keywordList.value,
      service: service.value || 'default',
      ref: refText.value,
      generate_images: generateImages.value,
      image_count: imageCount.value,
      use_schedule: autoSchedule.value,
      schedule_date: scheduleDate.value || undefined,
      schedule_start_hour: scheduleStartHour.value,
      schedule_interval_hours: scheduleIntervalHours.value,
      schedule_interval_minutes: scheduleIntervalMinutes.value,
      delay_between_posts: delayBetweenPosts.value,
    });

    const { success, generated = 0, published = 0, failed = 0, elapsed, results, error, message } = response.data;

    if (success) {
      addLog('SUCCESS', '전체 자동화 완료', `생성: ${generated}, 발행: ${published}, 실패: ${failed}, 소요: ${elapsed?.toFixed(1)}초`);
      if (results) {
        results.forEach((r: { manuscript_id: string; success: boolean; post_url?: string; error?: string }) => {
          if (r.success) {
            addLog('INFO', `원고 ${r.manuscript_id}`, r.post_url);
          } else {
            addLog('WARNING', `원고 ${r.manuscript_id}`, r.error);
          }
        });
      }
      keywords.value = '';
    } else {
      addLog('ERROR', '전체 자동화 실패', error || message);
    }
  } catch (error: unknown) {
    const axiosError = error as { code?: string; message?: string };
    const isTimeout = axiosError.code === 'ECONNABORTED' || axiosError.message?.includes('timeout');
    if (!isTimeout) {
      addLog('ERROR', '전체 자동화 실패', axiosError.message);
    }
  } finally {
    isBotRunning.value = false;
  }
};

onMounted(() => {
  addLog('INFO', '봇 페이지 초기화');
  checkAuthApiHealth();
});
</script>

<template>
  <div class="bot-page">
    <div class="bot-container">
      <!-- 왼쪽: 설정 패널 -->
      <div class="settings-panel">
        <Card class="panel-card">
          <!-- 로그인 카드 -->
          <div class="section login-section">
            <div class="section-header">
              <h3 class="section-title">네이버 계정</h3>
              <span :class="['status-badge', loginStatusClass]">
                {{ loginStatusLabel }}
              </span>
            </div>

            <!-- 계정 모드 토글 -->
            <div class="account-mode-toggle">
              <button
                :class="['mode-btn', { active: !useManualAccount }]"
                @click="useManualAccount = false"
              >
                프리셋
              </button>
              <button
                :class="['mode-btn', { active: useManualAccount }]"
                @click="useManualAccount = true"
              >
                직접입력
              </button>
            </div>

            <!-- 프리셋 모드 -->
            <div v-if="!useManualAccount" class="login-content">
              <div class="account-display">
                <span class="account-id">{{ ACCOUNTS[currentAccountIndex]?.id || '계정 없음' }}</span>
                <span v-if="ACCOUNTS.length > 1" class="account-count">
                  {{ currentAccountIndex + 1 }} / {{ ACCOUNTS.length }}
                </span>
              </div>
              <Button
                v-if="loginStatus !== 'LOGGED_IN'"
                size="sm"
                color="primary"
                :loading="isLoginLoading"
                class="login-btn"
                @click="handleLogin"
              >
                로그인
              </Button>
              <Button
                v-else
                size="sm"
                color="light"
                :loading="isLoginLoading"
                class="login-btn"
                @click="handleLogout"
              >
                로그아웃
              </Button>
            </div>

            <!-- 직접입력 모드 -->
            <div v-else class="manual-login-form">
              <div class="form-field">
                <input
                  v-model="manualId"
                  type="text"
                  class="field-input"
                  placeholder="네이버 아이디"
                  :disabled="loginStatus === 'LOGGED_IN'"
                />
              </div>
              <div class="form-field">
                <input
                  v-model="manualPassword"
                  type="password"
                  class="field-input"
                  placeholder="비밀번호"
                  :disabled="loginStatus === 'LOGGED_IN'"
                />
              </div>
              <Button
                v-if="loginStatus !== 'LOGGED_IN'"
                size="sm"
                color="primary"
                display="full"
                :loading="isLoginLoading"
                :disabled="!manualId || !manualPassword"
                @click="handleLogin"
              >
                로그인
              </Button>
              <Button
                v-else
                size="sm"
                color="light"
                display="full"
                :loading="isLoginLoading"
                @click="handleLogout"
              >
                로그아웃
              </Button>
            </div>
          </div>

          <!-- 구분선 -->
          <div class="divider" />

          <!-- 옵션 섹션 -->
          <div class="section options-section">
            <h3 class="section-title">발행 옵션</h3>
            <div class="options-grid">
              <label class="option-card">
                <Switch v-model="autoGenerateDraft" size="sm" />
                <div class="option-info">
                  <span class="option-name">원고 자동생성</span>
                  <span class="option-desc">{{ autoGenerateDraft ? 'AI 원고 생성' : '로컬 원고 사용' }}</span>
                </div>
              </label>
              <label class="option-card">
                <Switch v-model="autoSchedule" size="sm" />
                <div class="option-info">
                  <span class="option-name">예약 발행</span>
                  <span class="option-desc">지정 시간에 발행</span>
                </div>
              </label>
            </div>
          </div>

          <!-- 로컬 원고 업로드 (autoGenerateDraft = false) -->
          <div v-if="!autoGenerateDraft" class="section upload-section">
            <h3 class="section-title">원고 폴더 업로드</h3>
            <div
              class="drop-zone"
              :class="{ 'drop-zone-active': isDragOver }"
              @dragover="handleDragOver"
              @dragleave="handleDragLeave"
              @drop="handleDrop"
            >
              <div class="drop-zone-content">
                <span class="drop-icon">📁</span>
                <p class="drop-text">폴더를 여기에 드래그하세요</p>
                <p class="drop-hint">폴더 안에 원고.txt + images/ 구조</p>
              </div>
            </div>

            <!-- 업로드된 폴더 목록 -->
            <div v-if="uploadedFolderList.length > 0" class="folder-list">
              <div class="folder-list-header">
                <span class="folder-count">{{ uploadedFolderList.length }}개 폴더</span>
                <button class="clear-folder-btn" @click="clearFolderList">전체 삭제</button>
              </div>
              <ul class="folder-items">
                <li v-for="(folder, index) in uploadedFolderList" :key="folder.name" class="folder-item">
                  <div class="folder-info">
                    <span class="folder-name">{{ folder.name }}</span>
                    <span class="folder-meta">
                      {{ folder.manuscriptFile ? '📄' : '❌' }}
                      {{ folder.imageFiles.length }}장
                    </span>
                  </div>
                  <button class="remove-folder-btn" @click="removeFolder(index)">×</button>
                </li>
              </ul>
              <Button
                display="full"
                size="md"
                color="primary"
                :loading="isUploading"
                class="upload-btn"
                @click="handleUploadFolders"
              >
                서버에 업로드
              </Button>
            </div>
          </div>

          <!-- 원고 자동생성 설정 -->
          <div v-if="autoGenerateDraft" class="section generate-section">
            <h3 class="section-title">원고 생성 설정</h3>
            <div class="generate-form">
              <div class="form-field">
                <label class="field-label">키워드 (필수)</label>
                <textarea
                  v-model="keywords"
                  class="field-textarea"
                  placeholder="키워드 입력 (줄바꿈 또는 쉼표로 구분)&#10;예: 위고비 효과&#10;위고비 부작용&#10;위고비 가격"
                  rows="4"
                />
                <span class="field-hint">{{ keywordList.length }}개 키워드</span>
              </div>
              <div class="form-row">
                <div class="form-field">
                  <label class="field-label">카테고리</label>
                  <input
                    v-model="service"
                    type="text"
                    class="field-input"
                    placeholder="예: 위고비"
                  />
                </div>
                <div class="form-field">
                  <label class="field-label">이미지 수</label>
                  <input
                    v-model.number="imageCount"
                    type="number"
                    min="1"
                    max="10"
                    class="field-input"
                  />
                </div>
              </div>
              <div class="form-field">
                <label class="field-label">참조 원고 (선택)</label>
                <textarea
                  v-model="refText"
                  class="field-textarea"
                  placeholder="참조할 원고 내용 (선택)"
                  rows="3"
                />
              </div>
              <div class="form-row">
                <label class="option-item-inline">
                  <Switch v-model="generateImages" size="sm" />
                  <span>이미지 생성</span>
                </label>
                <div class="form-field-inline">
                  <label class="field-label">대기시간(초)</label>
                  <input
                    v-model.number="delayBetweenPosts"
                    type="number"
                    min="10"
                    max="300"
                    class="field-input-sm"
                  />
                </div>
              </div>
            </div>
          </div>

          <!-- 예약 설정 -->
          <div v-if="autoSchedule" class="section schedule-section">
            <h3 class="section-title">예약 설정</h3>
            <div class="schedule-grid">
              <div class="schedule-field">
                <label class="field-label">발행 날짜</label>
                <input
                  v-model="scheduleDate"
                  type="date"
                  :min="today"
                  class="field-input date-input"
                />
              </div>
              <div class="schedule-field">
                <label class="field-label">시작 시간</label>
                <div class="time-input-wrap">
                  <input
                    v-model.number="scheduleStartHour"
                    type="number"
                    min="0"
                    max="23"
                    class="field-input time-input"
                  />
                  <span class="time-suffix">시</span>
                </div>
              </div>
              <div class="schedule-field">
                <label class="field-label">간격 (시간)</label>
                <input
                  v-model.number="scheduleIntervalHours"
                  type="number"
                  min="0"
                  max="24"
                  class="field-input"
                />
              </div>
              <div class="schedule-field">
                <label class="field-label">간격 (분)</label>
                <input
                  v-model.number="scheduleIntervalMinutes"
                  type="number"
                  min="0"
                  max="59"
                  class="field-input"
                />
              </div>
            </div>
            <p class="schedule-hint">분 값이 0보다 크면 분 단위가 우선 적용됩니다</p>
          </div>

          <!-- 구분선 -->
          <div class="divider" />

          <!-- 액션 버튼 -->
          <div class="section action-section">
            <div class="action-buttons">
              <!-- 로컬 원고 모드 -->
              <template v-if="!autoGenerateDraft">
                <Button
                  size="md"
                  color="primary"
                  :loading="isPublishing"
                  :disabled="loginStatus !== 'LOGGED_IN' || isBotRunning"
                  class="action-btn"
                  @click="handlePublish"
                >
                  발행하기
                </Button>
                <Button
                  v-if="!isBotRunning"
                  size="md"
                  color="success"
                  :disabled="isPublishing"
                  class="action-btn"
                  @click="handleStartBot"
                >
                  자동화 시작
                </Button>
              </template>
              <!-- 원고 자동생성 모드 -->
              <template v-else>
                <Button
                  v-if="!isBotRunning"
                  size="md"
                  color="primary"
                  :disabled="keywordList.length === 0"
                  class="action-btn full-width"
                  @click="handleAutoBot"
                >
                  원고생성 + 발행 시작
                </Button>
              </template>
              <!-- 중지 버튼 -->
              <Button
                v-if="isBotRunning"
                size="md"
                color="danger"
                class="action-btn"
                @click="handleStopBot"
              >
                중지
              </Button>
            </div>
          </div>
        </Card>
      </div>

      <!-- 오른쪽: 로그 패널 -->
      <div class="log-panel">
        <Card class="panel-card log-card">
          <template #header>
            <div class="log-header">
              <h2 class="panel-title">실행 로그</h2>
              <button class="clear-btn" @click="clearLogs">
                지우기
              </button>
            </div>
          </template>

          <div ref="logContainer" class="log-container">
            <div
              v-for="log in logs"
              :key="log.id"
              :class="['log-entry', getLogClass(log.type)]"
            >
              <span class="log-icon">{{ getLogIcon(log.type) }}</span>
              <span class="log-time">{{ formatTime(log.timestamp) }}</span>
              <span class="log-message">{{ log.message }}</span>
              <span v-if="log.detail" class="log-detail">{{ log.detail }}</span>
            </div>
            <div v-if="logs.length === 0" class="log-empty">
              로그가 없습니다
            </div>
          </div>
        </Card>
      </div>
    </div>
  </div>
</template>

<style scoped>
.bot-page {
  padding: 24px;
  min-height: 100vh;
  background: linear-gradient(135deg, #0f0f1a 0%, #1a1a2e 50%, #16213e 100%);
}

.bot-container {
  display: grid;
  grid-template-columns: 380px 1fr;
  gap: 24px;
  max-width: 1400px;
  margin: 0 auto;
  height: calc(100vh - 48px);
}

.settings-panel,
.log-panel {
  height: 100%;
  overflow: hidden;
}

.panel-card {
  height: 100%;
  background: rgba(255, 255, 255, 0.03);
  backdrop-filter: blur(10px);
  border: 1px solid rgba(255, 255, 255, 0.08);
  border-radius: 16px;
  overflow: hidden;
}

.panel-card :deep(.card-body) {
  padding: 0;
  height: 100%;
  display: flex;
  flex-direction: column;
}

/* 섹션 공통 */
.section {
  padding: 20px 24px;
}

.section-header {
  display: flex;
  justify-content: space-between;
  align-items: center;
  margin-bottom: 16px;
}

.section-title {
  margin: 0;
  font-size: 14px;
  font-weight: 600;
  color: #a0aec0;
  text-transform: uppercase;
  letter-spacing: 0.5px;
}

.divider {
  height: 1px;
  background: linear-gradient(90deg, transparent, rgba(255, 255, 255, 0.1), transparent);
  margin: 0;
}

/* 상태 배지 */
.status-badge {
  padding: 4px 10px;
  border-radius: 20px;
  font-size: 11px;
  font-weight: 600;
  text-transform: uppercase;
}

.status-out {
  background: rgba(160, 174, 192, 0.2);
  color: #a0aec0;
}

.status-loading {
  background: rgba(251, 191, 36, 0.2);
  color: #fbbf24;
  animation: pulse 1.5s ease-in-out infinite;
}

.status-in {
  background: rgba(16, 185, 129, 0.2);
  color: #10b981;
}

.status-error {
  background: rgba(239, 68, 68, 0.2);
  color: #ef4444;
}

/* 로그인 섹션 */
.account-mode-toggle {
  display: flex;
  gap: 4px;
  padding: 4px;
  background: rgba(15, 23, 42, 0.4);
  border-radius: 8px;
  margin-bottom: 14px;
}

.mode-btn {
  flex: 1;
  padding: 8px 12px;
  font-size: 12px;
  font-weight: 500;
  color: #94a3b8;
  background: transparent;
  border: none;
  border-radius: 6px;
  cursor: pointer;
  transition: all 0.2s ease;
}

.mode-btn:hover {
  color: #e2e8f0;
}

.mode-btn.active {
  background: rgba(99, 102, 241, 0.3);
  color: #e2e8f0;
}

.login-content {
  display: flex;
  justify-content: space-between;
  align-items: center;
  gap: 16px;
}

.account-display {
  display: flex;
  flex-direction: column;
  gap: 2px;
}

.account-id {
  font-size: 15px;
  font-weight: 500;
  color: #e2e8f0;
}

.account-count {
  font-size: 11px;
  color: #64748b;
}

.login-btn {
  min-width: 80px;
}

.manual-login-form {
  display: flex;
  flex-direction: column;
  gap: 10px;
}

.manual-login-form .form-field {
  margin: 0;
}

.manual-login-form .field-input {
  height: 38px;
}

/* 옵션 섹션 */
.options-section .section-title {
  margin-bottom: 16px;
}

.options-grid {
  display: flex;
  flex-direction: column;
  gap: 12px;
}

.option-card {
  display: flex;
  align-items: center;
  gap: 14px;
  padding: 14px 16px;
  background: rgba(255, 255, 255, 0.02);
  border: 1px solid rgba(255, 255, 255, 0.06);
  border-radius: 12px;
  cursor: pointer;
  transition: all 0.2s ease;
}

.option-card:hover {
  background: rgba(255, 255, 255, 0.04);
  border-color: rgba(255, 255, 255, 0.1);
}

.option-info {
  display: flex;
  flex-direction: column;
  gap: 2px;
}

.option-name {
  font-size: 14px;
  font-weight: 500;
  color: #e2e8f0;
}

.option-desc {
  font-size: 11px;
  color: #64748b;
}

/* 예약 설정 */
.schedule-section {
  background: rgba(99, 102, 241, 0.05);
  border-top: 1px solid rgba(99, 102, 241, 0.1);
  border-bottom: 1px solid rgba(99, 102, 241, 0.1);
}

.schedule-grid {
  display: grid;
  grid-template-columns: 1fr 1fr;
  gap: 14px;
}

.schedule-field {
  display: flex;
  flex-direction: column;
  gap: 6px;
}

.field-label {
  font-size: 11px;
  font-weight: 500;
  color: #94a3b8;
  text-transform: uppercase;
  letter-spacing: 0.3px;
}

.field-input {
  height: 40px;
  padding: 0 12px;
  background: rgba(15, 23, 42, 0.6);
  border: 1px solid rgba(255, 255, 255, 0.1);
  border-radius: 8px;
  font-size: 14px;
  color: #e2e8f0;
  transition: all 0.2s ease;
}

.field-input:focus {
  outline: none;
  border-color: #6366f1;
  box-shadow: 0 0 0 3px rgba(99, 102, 241, 0.15);
}

.date-input {
  color-scheme: dark;
}

.time-input-wrap {
  display: flex;
  align-items: center;
  gap: 8px;
}

.time-input {
  width: 70px;
  text-align: center;
}

.time-suffix {
  font-size: 13px;
  color: #64748b;
}

.schedule-hint {
  margin: 12px 0 0;
  font-size: 11px;
  color: #64748b;
  text-align: center;
}

/* 원고 생성 폼 */
.generate-section {
  background: rgba(16, 185, 129, 0.05);
  border-top: 1px solid rgba(16, 185, 129, 0.1);
  border-bottom: 1px solid rgba(16, 185, 129, 0.1);
}

.generate-form {
  display: flex;
  flex-direction: column;
  gap: 14px;
}

.form-field {
  display: flex;
  flex-direction: column;
  gap: 6px;
}

.form-row {
  display: grid;
  grid-template-columns: 1fr 1fr;
  gap: 12px;
  align-items: end;
}

.field-textarea {
  padding: 10px 12px;
  background: rgba(15, 23, 42, 0.6);
  border: 1px solid rgba(255, 255, 255, 0.1);
  border-radius: 8px;
  font-size: 13px;
  color: #e2e8f0;
  resize: vertical;
  min-height: 80px;
  font-family: inherit;
  transition: all 0.2s ease;
}

.field-textarea:focus {
  outline: none;
  border-color: #10b981;
  box-shadow: 0 0 0 3px rgba(16, 185, 129, 0.15);
}

.field-textarea::placeholder {
  color: #64748b;
}

.field-hint {
  font-size: 10px;
  color: #10b981;
  text-align: right;
}

.option-item-inline {
  display: flex;
  align-items: center;
  gap: 8px;
  font-size: 13px;
  color: #e2e8f0;
  cursor: pointer;
}

.form-field-inline {
  display: flex;
  align-items: center;
  gap: 8px;
}

.form-field-inline .field-label {
  margin: 0;
  white-space: nowrap;
}

.field-input-sm {
  width: 70px;
  height: 32px;
  padding: 0 8px;
  background: rgba(15, 23, 42, 0.6);
  border: 1px solid rgba(255, 255, 255, 0.1);
  border-radius: 6px;
  font-size: 13px;
  color: #e2e8f0;
  text-align: center;
}

.field-input-sm:focus {
  outline: none;
  border-color: #10b981;
}

.full-width {
  width: 100%;
}

/* 액션 버튼 */
.action-section {
  margin-top: auto;
  padding: 20px 24px 24px;
}

.action-buttons {
  display: flex;
  gap: 12px;
}

.action-btn {
  flex: 1;
  height: 44px;
  font-weight: 600;
}

/* 로그 패널 */
.log-card {
  display: flex;
  flex-direction: column;
}

.log-card :deep(.card-header) {
  padding: 16px 20px;
  border-bottom: 1px solid rgba(255, 255, 255, 0.06);
}

.log-card :deep(.card-body) {
  flex: 1;
  overflow: hidden;
  padding: 0;
}

.log-header {
  display: flex;
  justify-content: space-between;
  align-items: center;
}

.panel-title {
  margin: 0;
  font-size: 15px;
  font-weight: 600;
  color: #e2e8f0;
}

.clear-btn {
  padding: 6px 12px;
  font-size: 12px;
  font-weight: 500;
  color: #64748b;
  background: rgba(255, 255, 255, 0.05);
  border: 1px solid rgba(255, 255, 255, 0.08);
  border-radius: 6px;
  cursor: pointer;
  transition: all 0.2s ease;
}

.clear-btn:hover {
  background: rgba(255, 255, 255, 0.08);
  color: #94a3b8;
}

.log-container {
  height: 100%;
  overflow-y: auto;
  padding: 12px 16px;
  font-family: 'JetBrains Mono', 'SF Mono', Monaco, monospace;
  font-size: 12px;
  background: rgba(15, 23, 42, 0.4);
}

.log-entry {
  display: flex;
  gap: 10px;
  padding: 8px 12px;
  border-radius: 8px;
  margin-bottom: 4px;
  align-items: flex-start;
  transition: background 0.15s ease;
}

.log-entry:hover {
  background: rgba(255, 255, 255, 0.03);
}

.log-icon {
  flex-shrink: 0;
  font-size: 11px;
}

.log-time {
  flex-shrink: 0;
  color: #475569;
  font-size: 11px;
}

.log-message {
  color: #cbd5e1;
  word-break: break-word;
}

.log-detail {
  color: #64748b;
  font-size: 11px;
  word-break: break-all;
}

.log-info { background: rgba(59, 130, 246, 0.08); }
.log-success { background: rgba(16, 185, 129, 0.08); }
.log-error { background: rgba(239, 68, 68, 0.12); }
.log-warning { background: rgba(251, 191, 36, 0.08); }

.log-info .log-message { color: #60a5fa; }
.log-success .log-message { color: #34d399; }
.log-error .log-message { color: #f87171; }
.log-error .log-detail { color: #fca5a5; }
.log-warning .log-message { color: #fbbf24; }

.log-empty {
  display: flex;
  align-items: center;
  justify-content: center;
  height: 100%;
  color: #475569;
  font-size: 13px;
}

@keyframes pulse {
  0%, 100% { opacity: 1; }
  50% { opacity: 0.6; }
}

/* 폴더 업로드 섹션 */
.upload-section {
  background: rgba(59, 130, 246, 0.05);
  border-top: 1px solid rgba(59, 130, 246, 0.1);
  border-bottom: 1px solid rgba(59, 130, 246, 0.1);
}

.drop-zone {
  padding: 32px 20px;
  border: 2px dashed rgba(99, 102, 241, 0.3);
  border-radius: 12px;
  background: rgba(15, 23, 42, 0.4);
  text-align: center;
  cursor: pointer;
  transition: all 0.2s ease;
}

.drop-zone:hover,
.drop-zone-active {
  border-color: #6366f1;
  background: rgba(99, 102, 241, 0.1);
}

.drop-zone-content {
  display: flex;
  flex-direction: column;
  align-items: center;
  gap: 8px;
}

.drop-icon {
  font-size: 32px;
}

.drop-text {
  margin: 0;
  font-size: 14px;
  font-weight: 500;
  color: #e2e8f0;
}

.drop-hint {
  margin: 0;
  font-size: 11px;
  color: #64748b;
}

.folder-list {
  margin-top: 16px;
}

.folder-list-header {
  display: flex;
  justify-content: space-between;
  align-items: center;
  margin-bottom: 10px;
}

.folder-count {
  font-size: 12px;
  font-weight: 500;
  color: #94a3b8;
}

.clear-folder-btn {
  padding: 4px 8px;
  font-size: 11px;
  color: #ef4444;
  background: transparent;
  border: 1px solid rgba(239, 68, 68, 0.3);
  border-radius: 4px;
  cursor: pointer;
  transition: all 0.2s ease;
}

.clear-folder-btn:hover {
  background: rgba(239, 68, 68, 0.1);
}

.folder-items {
  list-style: none;
  margin: 0;
  padding: 0;
  display: flex;
  flex-direction: column;
  gap: 6px;
  max-height: 150px;
  overflow-y: auto;
}

.folder-item {
  display: flex;
  justify-content: space-between;
  align-items: center;
  padding: 10px 12px;
  background: rgba(255, 255, 255, 0.03);
  border: 1px solid rgba(255, 255, 255, 0.06);
  border-radius: 8px;
}

.folder-info {
  display: flex;
  align-items: center;
  gap: 10px;
}

.folder-name {
  font-size: 13px;
  font-weight: 500;
  color: #e2e8f0;
}

.folder-meta {
  font-size: 11px;
  color: #64748b;
}

.remove-folder-btn {
  width: 22px;
  height: 22px;
  padding: 0;
  font-size: 14px;
  color: #64748b;
  background: transparent;
  border: none;
  border-radius: 4px;
  cursor: pointer;
  transition: all 0.15s ease;
}

.remove-folder-btn:hover {
  color: #ef4444;
  background: rgba(239, 68, 68, 0.1);
}

.upload-btn {
  margin-top: 12px;
}

@media (max-width: 900px) {
  .bot-container {
    grid-template-columns: 1fr;
    height: auto;
  }

  .settings-panel {
    height: auto;
  }

  .log-panel {
    height: 400px;
  }
}
</style>
